### PR TITLE
Fix env_var() resolution and LSP shutdown

### LINKED ISSUE #8: Env vars from direnv are not loaded
First I want to say thank you for this project, I have been wanting something like this for a while and even considered (and started, barely) building this myself without success so this is great to see!

My dbt projects all use direnv and a `.envrc` file to define a bunch of env vars relevant to the project but those differ from project to project so direnv has been the solution so far.

Here are some example env vars that are in the `.envrc` file:
- export DBT_PROFILE="name"
- DBT_PROFILES_DIR="path/"
- DBT_MANIFEST_PATH="path/"
- DBT_PROJECT_DIR="path/"

Having a look at the logs for Helix and the LSP, I can see this:
```
2026-02-25T15:08:49.537 helix_lsp::transport [ERROR] dbt-language-server err <- "2026/02/25 15:08:49 Key not found: {{ env_var(\"DBT_PROFILE\") }}\n"
2026-02-25T15:09:10.080 helix_lsp::transport [ERROR] dbt-language-server err <- "2026/02/25 15:09:10 Key not found: {{ env_var(\"DBT_PROFILE\") }}\n"
2026-02-25T15:17:41.723 helix_term::application [ERROR] Timed out waiting for language servers to shutdown
2026-02-25T15:17:41.725 helix_lsp::transport [ERROR] Could not close request on a closed channel (id=Num(2))
2026-02-25T15:17:41.725 helix_lsp::transport [ERROR] err: <- Other(failed to send a message to server
```
For context, `{{ env_var("DBT_PROFILE") }}` is in `dbt_project.yml` and I started helix from a shell (fish) that had the env vars loaded.

I tried to investigate a bit and it is hard to know (from my limited knowledge of golang and this project) where the issue is coming from but if you have tests you'd like me to run I would be happy to help!

Thanks again!

### PR DESCRIPTION
**Pull request by theodotdot**
## Summary
- Resolve `{{ env_var() }}` jinja expressions in `dbt_project.yml` before YAML parsing, so fields like `profile` that use environment variables are correctly read
- Handle `shutdown` and `exit` LSP methods so editors don't timeout waiting for the server to stop

Fixes #8

## Test plan
- [x] Added unit tests for `env_var()` resolution (with/without defaults, missing vars, multiple expressions)
- [x] All existing tests pass
- [x] Manual testing with Helix editor — env vars resolve correctly, clean shutdown on quit

### CODE REVIEW

File: util/resolve_env_vars.go [hunk 1]
```diff
@@ -0,0 +1,27 @@
...
+		value, exists := os.LookupEnv(varName)
+		if exists {
+			return value
+		}
+
+		if submatches[4] != "" {
+			return defaultValue
+		}
+
+		return match
```
Comment (j-clemons) [inline util/resolve_env_vars.go]: When testing with an env var that is not set, I am not getting a default value returned but am just getting the original jinja string which results in the parse failure and lsp being unfunctional. I would prefer to default to a hardcoded default value based on the var name.
